### ISSUE TITLE
Missing information in Readme.md

### ISSUE THREAD

**Issue by proclamo-zz** [FabienPennequin/FPNTagBundle#2]
In autoload.php:

$loader->registerNamespaces(array(
...

'DoctrineExtensions' => **DIR**.'/../vendor/doctrine-extensions-taggable/lib',

));

and in app/config.yml:

fpn_tag:
  model:
    tag_class: FPN\TagBundle\Entity\Tag
    tagging_class: FPN\TagBundle\Entity\Tagging

**Comment by leevigraham** [comment]
This also fixed my issue but raises another one (I think).

I don't think the autoloader should use 'DoctrineExtensions' as the key. I'm also using @l3pp4rd's doctrine extensions [implemented in Symfony2](https://github.com/stof/StofDoctrineExtensionsBundle) by @stof.

I'm still feeling my way around Symfony2 so I can't offer a pull request or clearly identify the issue. Happy to be told that I'm wrong but isn't there a chance of naming conflicts when using 'DoctrineExtensions'?

**Comment by stof** [comment]
There is a conflict as `DoctrineExtensions` is already used as namespace by @beberlei (who is Doctrine lead dev)

**Comment by l3pp4rd** [comment]
Yes, try to think some vendor namespace of your own, it will conflict otherwise

**Comment by leevigraham** [comment]
@stof / @l3pp4rd Thanks for confirming my initial thoughts. Time to look deeper into DI so I can create a PR :D

**Comment by leevigraham** [comment]
I've created a separate issue for the potential autoloader conflict naming here: https://github.com/FabienPennequin/FPNTagBundle/issues/3

**Comment by stof** [comment]
Well, the first step is not about DI. It is about changing the namespace of the related library to something else. And this should be let to the owner so that he choose the name he wants to use.
