### ISSUE TITLE
There is no column with name 'resource_type' on table 'Tag'

### ISSUE THREAD

**Issue by gristoi** [FabienPennequin/FPNTagBundle#20]
I have followed your installation instructions to the letter, but when i try to run schema:update on my app i am getting the above error.
In my new Tag Entity:

@ORM\Table(uniqueConstraints={@UniqueConstraint(name="tagging_idx", columns={"tag_id", "resource_type", "resource_id"})})

Any Idea what i am doing wrong, or is this a bug

**Comment by daikiridev** [comment]
Hello,

Any idea on how to solve this ?
On my side, when I specify a table name:

@ORM\Table(name="my_tagging",uniqueConstraints={@UniqueConstraint(name="tagging_idx", columns={"tag_id", "resource_type", "resource_id"})})
I got the same messageas you had.

When table name is not mentionned, I got:

[Doctrine\DBAL\Schema\SchemaException] The table with name 'mydb.tagging' already exists.

I also tried https://github.com/fogs/tagging-bundle, which has got plenty of configuration errors when installing it...

DDev
