### ISSUE TITLE
Please tag a version

### ISSUE THREAD

**Issue by tarjei** [FabienPennequin/FPNTagBundle#23]
Hi, I see this great bundle has been virtually unchanged the last year.

Would you please create a version for it so that I do not have to check for dev-master every time I do an install?

kind regards,
Tarjei

**Comment by garak** [comment]
:+1:

**Comment by garak** [comment]
You also need to tag dependencies. See https://github.com/FabienPennequin/DoctrineExtensions-Taggable/issues/18

**Comment by hilobok** [comment]
:+1:

**Comment by rvanlaak** [comment]
+1

**Comment by rvanlaak** [comment]
ping @FabienPennequin

**Comment by FabienPennequin** [comment]
Done, see v0.9.0

**Comment by RolfBabijn** [comment]
Thank you for releasing a tag! My dependency list looks much cleaner now. +1
