### ISSUE TITLE
 Hierarchical tags

### ISSUE THREAD

**Issue by daturon** [FabienPennequin/FPNTagBundle#27]
Somebody knows about creating hierarchical tags on FPNTagBundle?

**Comment by aosmialowski** [comment]
@daturon no solution, but could you please share your idea of hierarchical tags? What are you trying to achieve?

**Comment by daturon** [comment]
@aosmialowski I wanted to have several dictionaries with a tree structure.

**Comment by gvoxel** [comment]
Hey. Me too create hierarchical tree tags. Please, help with solution.
