### ISSUE TITLE
doctrine-extensions-taggable

### ISSUE THREAD

**Issue by bonswouar** [FabienPennequin/FPNTagBundle#32]
I'm already using some doctrine extensions with the bundle [gedmo/doctrine-extensions](https://github.com/Atlantic18/DoctrineExtensions) which include them all.
But your Bundle depends on `fpn/doctrine-extensions-taggable`, which only includes the taggable behaviour of Doctrine Extensions.
How could I manage that, without having the same library twice ?

**Comment by jbouzekri** [comment]
I am looking at the gedmo doctrine extensions but I don't see any taggable behaviours. So If you want to use this bundle you must use our dependency.

Moreover for now our taggable extension is dependent of an external service TagManager which must be called to hydrate and manipulate the tags of an entity. So with this philosophy, I don't think we can merge it in the gedmo extensions.
