### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by HenriVesala** [FabienPennequin/FPNTagBundle#5]
fpn_tag:
    model:
        tag_class:     Acme\TagBundle\Entity\Tag
        tagging_class: Acme\TagBundle\Entity\Tag    (should be tagging_class: Acme\TagBundle\Entity\Tagging)

Also in "Making an Entity Taggable" entity uses "$this->tags" but its not defined.

**Comment by FabienPennequin** [comment]
Fixed with pull request #6.
